spring.application.name=AnalyticsService
spring.datasource.url=jdbc:postgresql://postgres:5432/rcmor
spring.datasource.username=rcmor
spring.datasource.password=rcmor
spring.jpa.hibernate.ddl-auto=none
